Repository mash-up-kr/NoWeekend-Server, pull requests merged in 2025-05, with the labels that each got.

#1 fix: make gradlew executable to fix CI lint step failure
  .github/workflows/ci.yml
Labels: fix, 준형

#2 chore: add initial GitHub repository settings (CODEOWNERS, PR template)
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 준형, chore

#3 feat: initialize MCP server with Spring Boot
  noweekend-mcp/mcp-server/.editorconfig
  noweekend-mcp/mcp-server/.gitattributes
  noweekend-mcp/mcp-server/.gitignore
  noweekend-mcp/mcp-server/build.gradle.kts
  noweekend-mcp/mcp-server/gradlew
  noweekend-mcp/mcp-server/gradlew.bat
  noweekend-mcp/mcp-server/settings.gradle.kts
  noweekend-mcp/mcp-server/src/main/kotlin/noweekend/mcpserver/McpServerApplication.kt
  noweekend-mcp/mcp-server/src/main/kotlin/noweekend/mcpserver/client/ClimateClient.kt
  noweekend-mcp/mcp-server/src/main/kotlin/noweekend/mcpserver/config/FeignClientConfig.kt
  noweekend-mcp/mcp-server/src/main/kotlin/noweekend/mcpserver/config/ToolCallbackProviderConfig.kt
  noweekend-mcp/mcp-server/src/main/kotlin/noweekend/mcpserver/tool/FutureWeatherTool.kt
  noweekend-mcp/mcp-server/src/main/kotlin/noweekend/mcpserver/tool/dto/ClimateResponse.kt
  noweekend-mcp/mcp-server/src/main/kotlin/noweekend/mcpserver/tool/dto/DailyClimateData.kt
  noweekend-mcp/mcp-server/src/main/kotlin/noweekend/mcpserver/tool/dto/FutureWeatherRequest.kt
  noweekend-mcp/mcp-server/src/main/resources/application.yml
Labels: feat, 준형

#4 feat: initialize MCP host with Spring Boot
  noweekend-mcp/mcp-host/.gitattributes
  noweekend-mcp/mcp-host/.gitignore
  noweekend-mcp/mcp-host/build.gradle.kts
  noweekend-mcp/mcp-host/gradlew
  noweekend-mcp/mcp-host/gradlew.bat
  noweekend-mcp/mcp-host/settings.gradle.kts
  noweekend-mcp/mcp-host/src/main/kotlin/noweekend/mcphost/McpHostApplication.kt
  noweekend-mcp/mcp-host/src/main/kotlin/noweekend/mcphost/config/ChatConfig.kt
  noweekend-mcp/mcp-host/src/main/kotlin/noweekend/mcphost/controller/ChatBotDto.kt
  noweekend-mcp/mcp-host/src/main/kotlin/noweekend/mcphost/controller/ChatbotController.kt
  noweekend-mcp/mcp-host/src/main/kotlin/noweekend/mcphost/service/ChatbotService.kt
  noweekend-mcp/mcp-host/src/main/resources/application.yml
Labels: feat, 준형

#5 chore: add ktlint formatting to mcp modules & speed up CI checks
  .github/workflows/ci-develop.yml
  .github/workflows/ci-prod.yml
  .github/workflows/ci.yml
  noweekend-mcp/mcp-host/.editorconfig
  noweekend-mcp/mcp-host/build.gradle.kts
  noweekend-mcp/mcp-host/gradlew
  noweekend-mcp/mcp-host/src/main/kotlin/noweekend/mcphost/config/ChatConfig.kt
  noweekend-mcp/mcp-host/src/main/kotlin/noweekend/mcphost/controller/ChatBotDto.kt
  noweekend-mcp/mcp-host/src/main/kotlin/noweekend/mcphost/controller/ChatbotController.kt
  noweekend-mcp/mcp-host/src/main/kotlin/noweekend/mcphost/service/ChatbotService.kt
  noweekend-mcp/mcp-server/build.gradle.kts
  noweekend-mcp/mcp-server/gradlew
  noweekend-mcp/mcp-server/src/main/kotlin/noweekend/mcpserver/client/ClimateClient.kt
  noweekend-mcp/mcp-server/src/main/kotlin/noweekend/mcpserver/config/FeignClientConfig.kt
  noweekend-mcp/mcp-server/src/main/kotlin/noweekend/mcpserver/config/ToolCallbackProviderConfig.kt
  noweekend-mcp/mcp-server/src/main/kotlin/noweekend/mcpserver/tool/FutureWeatherTool.kt
  noweekend-mcp/mcp-server/src/main/kotlin/noweekend/mcpserver/tool/dto/ClimateResponse.kt
  noweekend-mcp/mcp-server/src/main/kotlin/noweekend/mcpserver/tool/dto/DailyClimateData.kt
  noweekend-mcp/mcp-server/src/main/kotlin/noweekend/mcpserver/tool/dto/FutureWeatherRequest.kt
Labels: feat, 준형

#6 feat: add client-mcp module for communicating with mcp-host via Feign
  noweekend-clients/client-mcp/build.gradle.kts
  noweekend-clients/client-mcp/src/main/kotlin/noweekend/client/ChatbotApi.kt
  noweekend-clients/client-mcp/src/main/kotlin/noweekend/client/ChatbotClient.kt
  noweekend-clients/client-mcp/src/main/kotlin/noweekend/client/FeignConfig.kt
  noweekend-clients/client-mcp/src/main/kotlin/noweekend/client/model/Chat.kt
  noweekend-clients/client-mcp/src/main/resources/client-mcp.yml
  noweekend-core/core-api/build.gradle.kts
  noweekend-core/core-api/src/main/resources/application.yml
  noweekend-mcp/mcp-host/src/main/kotlin/noweekend/mcphost/controller/ChatbotController.kt
  settings.gradle.kts
Labels: feat, 준형

#7 merge: merge feature/security-config into develop
  noweekend-core/core-api/build.gradle.kts
  noweekend-core/core-api/src/main/kotlin/noweekend/core/api/core/api/config/SecurityConfig.kt
  noweekend-core/core-api/src/main/kotlin/noweekend/core/api/core/api/security/authentication/AuthenticatedUserToken.kt
  noweekend-core/core-api/src/main/kotlin/noweekend/core/api/core/api/security/authentication/UserAuthenticationToken.kt
  noweekend-core/core-api/src/main/kotlin/noweekend/core/api/core/api/security/filter/JwtAuthenticationFilter.kt
  noweekend-core/core-api/src/main/kotlin/noweekend/core/api/core/api/security/jwt/JwtProvider.kt
  noweekend-core/core-api/src/main/kotlin/noweekend/core/api/core/api/security/jwt/JwtProviderImpl.kt
  noweekend-core/core-api/src/main/kotlin/noweekend/core/api/core/api/security/provider/JwtAuthenticationProvider.kt
  noweekend-core/core-api/src/main/kotlin/noweekend/core/api/core/support/error/ErrorCode.kt
  noweekend-core/core-api/src/main/kotlin/noweekend/core/api/core/support/error/ErrorType.kt
  noweekend-core/core-api/src/main/resources/application.yml
Labels: feat, 재민

#8 merge: merge feature/jasypt-config into develop
  noweekend-core/core-api/build.gradle.kts
  noweekend-core/core-api/src/main/kotlin/noweekend/core/api/core/api/config/JasyptConfig.kt
  noweekend-core/core-api/src/main/resources/application.yml
  noweekend-core/core-api/src/test/kotlin/noweekend/core/api/core/api/config/JasyptConfigTest.kt
Labels: feat, 재민, Do not merge
