Repository mash-up-kr/NoWeekend-Server, pull requests merged in 2025-06, with the labels that each got.

#9 feat: adding LangGraph, managing as task Node
  noweekend-mcp/mcp-host/build.gradle.kts
  noweekend-mcp/mcp-host/src/main/kotlin/noweekend/mcphost/config/LangGraphConfig.kt
  noweekend-mcp/mcp-host/src/main/kotlin/noweekend/mcphost/config/MyAgentState.kt
  noweekend-mcp/mcp-host/src/main/kotlin/noweekend/mcphost/controller/ChatbotController.kt
  noweekend-mcp/mcp-host/src/main/kotlin/noweekend/mcphost/service/GraphChatService.kt
Labels: feat, 준형, chore

#14 docs: swagger setting
  noweekend-core/core-api/build.gradle.kts
  noweekend-core/core-api/src/main/kotlin/noweekend/core/api/config/SecurityConfig.kt
  noweekend-core/core-api/src/main/kotlin/noweekend/core/api/config/SwaggerConfig.kt
  noweekend-core/core-api/src/main/kotlin/noweekend/core/api/controller/HealthController.kt
  noweekend-core/core-api/src/main/kotlin/noweekend/core/api/controller/v1/AuthController.kt
  noweekend-core/core-api/src/main/kotlin/noweekend/core/api/controller/v1/request/LoginRequest.kt
  noweekend-core/core-api/src/main/kotlin/noweekend/core/api/controller/v1/response/GoogleLoginResponse.kt
Labels: 준형, chore

#16 feat: oauth
  noweekend-clients/client-oauth/src/main/kotlin/noweekend/client/apple/AppleApi.kt
  noweekend-clients/client-oauth/src/main/kotlin/noweekend/client/apple/AppleClient.kt
  noweekend-clients/client-oauth/src/main/kotlin/noweekend/client/apple/AppleLoginParams.kt
  noweekend-clients/client-oauth/src/main/kotlin/noweekend/client/apple/AppleOAuthInfo.kt
  noweekend-clients/client-oauth/src/main/kotlin/noweekend/client/apple/ApplePublicKeyResponse.kt
  noweekend-clients/client-oauth/src/main/kotlin/noweekend/client/apple/AppleTokens.kt
  noweekend-clients/client-oauth/src/main/kotlin/noweekend/client/common/OAuthClient.kt
  noweekend-clients/client-oauth/src/main/kotlin/noweekend/client/common/OAuthInfo.kt
  noweekend-clients/client-oauth/src/main/kotlin/noweekend/client/common/OAuthLoginParams.kt
  noweekend-clients/client-oauth/src/main/kotlin/noweekend/client/common/Revocable.kt
  noweekend-clients/client-oauth/src/main/kotlin/noweekend/client/config/ComponentScanConfig.kt
  noweekend-clients/client-oauth/src/main/kotlin/noweekend/client/config/OAuthConfig.kt
  noweekend-clients/client-oauth/src/main/kotlin/noweekend/client/config/OAuthFeignConfig.kt
  noweekend-clients/client-oauth/src/main/kotlin/noweekend/client/google/GoogleClient.kt
  noweekend-clients/client-oauth/src/main/kotlin/noweekend/client/google/GoogleLoginParams.kt
  noweekend-clients/client-oauth/src/main/kotlin/noweekend/client/google/GoogleOAuthInfo.kt
  noweekend-clients/client-oauth/src/main/kotlin/noweekend/client/google/GoogleResourceApi.kt
  noweekend-clients/client-oauth/src/main/kotlin/noweekend/client/google/GoogleTokenApi.kt
  noweekend-clients/client-oauth/src/main/kotlin/noweekend/client/google/GoogleTokens.kt
  noweekend-clients/client-oauth/src/main/kotlin/noweekend/client/google/GoogleUserInfoRequest.kt
  noweekend-clients/client-oauth/src/main/kotlin/noweekend/client/google/GoogleUserInfoResponse.kt
  noweekend-clients/client-oauth/src/main/kotlin/noweekend/client/properties/AppleAuthProperties.kt
  noweekend-clients/client-oauth/src/main/kotlin/noweekend/client/properties/GoogleAuthProperties.kt
  noweekend-clients/client-oauth/src/main/resources/client-oauth.yml
  noweekend-core/core-api/src/main/kotlin/noweekend/core/api/controller/v1/AuthController.kt
  noweekend-core/core-api/src/main/kotlin/noweekend/core/api/controller/v1/request/LoginRequest.kt
  noweekend-core/core-api/src/main/kotlin/noweekend/core/api/controller/v1/response/OAuthLoginResponse.kt
  noweekend-core/core-api/src/main/kotlin/noweekend/core/domain/auth/AuthApplicationService.kt
  noweekend-core/core-api/src/main/kotlin/noweekend/core/domain/auth/AuthApplicationServiceImpl.kt
  noweekend-core/core-domain/build.gradle.kts
  noweekend-core/core-domain/src/main/kotlin/noweekend/core/domain/auth/AuthService.kt
  noweekend-core/core-domain/src/main/kotlin/noweekend/core/domain/user/User.kt
  noweekend-core/core-domain/src/main/kotlin/noweekend/core/domain/user/UserReader.kt
  noweekend-core/core-domain/src/main/kotlin/noweekend/core/domain/user/UserRepository.kt
  noweekend-storage/db-core/src/main/kotlin/noweekend/storage/db/core/user/UserCoreRepository.kt
  noweekend-storage/db-core/src/main/kotlin/noweekend/storage/db/core/user/UserEntity.kt
  noweekend-storage/db-core/src/main/kotlin/noweekend/storage/db/core/user/UserQueryDslRepository.kt
Labels: feat, 재민

#19 docs: add onboarding Schedules
  noweekend-core/core-api/src/main/kotlin/noweekend/core/api/controller/v1/UserController.kt
  noweekend-core/core-api/src/main/kotlin/noweekend/core/api/controller/v1/UserControllerDocs.kt
  noweekend-core/core-api/src/main/kotlin/noweekend/core/api/controller/v1/request/LeaveInputRequest.kt
  noweekend-core/core-api/src/main/kotlin/noweekend/core/api/controller/v1/request/OnboardingRequest.kt
  noweekend-core/core-api/src/main/kotlin/noweekend/core/api/controller/v1/request/ScheduleRequest.kt
  noweekend-core/core-api/src/main/kotlin/noweekend/core/api/controller/v1/request/ValidLeaveHours.kt
Labels: 준형
